export const FETCH_ADMINISTRATORS_SUCCESS = 'FETCH_ADMINISTRATORS_SUCCESS';
export const FETCH_ADMINISTRATORS_FAILURE = 'FETCH_ADMINISTRATORS_FAILURE';
export const ADD_ADMINISTRATOR_SUCCESS = 'ADD_ADMINISTRATOR_SUCCESS';
export const ADD_ADMINISTRATOR_FAILURE = 'ADD_ADMINISTRATOR_FAILURE';
export const EDIT_ADMINISTRATOR_SUCCESS = 'EDIT_ADMINISTRATOR_SUCCESS';
export const EDIT_ADMINISTRATOR_FAILURE = 'EDIT_ADMINISTRATOR_FAILURE';
export const DELETE_ADMINISTRATOR_SUCCESS = 'DELETE_ADMINISTRATOR_SUCCESS';
export const DELETE_ADMINISTRATOR_FAILURE = 'DELETE_ADMINISTRATOR_FAILURE';

export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_FAILURE = 'ADD_DEPARTMENT_FAILURE';
export const EDIT_DEPARTMENT_SUCCESS = 'EDIT_DEPARTMENT_SUCCESS';
export const EDIT_DEPARTMENT_FAILURE = 'EDIT_DEPARTMENT_FAILURE';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';
export const FETCH_DEPARTMENT_TYPES_SUCCESS = 'FETCH_DEPARTMENT_TYPES_SUCCESS';
export const FETCH_DEPARTMENT_TYPES_FAILURE = 'FETCH_DEPARTMENT_TYPES_FAILURE';

export const FETCH_GENERAL_PRACTITIONERS_SUCCESS = 'FETCH_GENERAL_PRACTITIONERS_SUCCESS';
export const FETCH_GENERAL_PRACTITIONERS_FAILURE = 'FETCH_GENERAL_PRACTITIONERS_FAILURE';
export const ADD_GENERAL_PRACTITIONER_SUCCESS = 'ADD_GENERAL_PRACTITIONER_SUCCESS';
export const ADD_GENERAL_PRACTITIONER_FAILURE = 'ADD_GENERAL_PRACTITIONER_FAILURE';
export const EDIT_GENERAL_PRACTITIONER_SUCCESS = 'EDIT_GENERAL_PRACTITIONER_SUCCESS';
export const EDIT_GENERAL_PRACTITIONER_FAILURE = 'EDIT_GENERAL_PRACTITIONER_FAILURE';
export const DELETE_GENERAL_PRACTITIONER_SUCCESS = 'DELETE_GENERAL_PRACTITIONER_SUCCESS';
export const DELETE_GENERAL_PRACTITIONER_FAILURE = 'DELETE_GENERAL_PRACTITIONER_FAILURE';

export const FETCH_HOSPITALS_SUCCESS = 'FETCH_HOSPITALS_SUCCESS';
export const FETCH_HOSPITALS_FAILURE = 'FETCH_HOSPITALS_FAILURE';
export const ADD_HOSPITAL_SUCCESS = 'ADD_HOSPITAL_SUCCESS';
export const ADD_HOSPITAL_FAILURE = 'ADD_HOSPITAL_FAILURE';
export const EDIT_HOSPITAL_SUCCESS = 'EDIT_HOSPITAL_SUCCESS';
export const EDIT_HOSPITAL_FAILURE = 'EDIT_HOSPITAL_FAILURE';
export const DELETE_HOSPITAL_SUCCESS = 'DELETE_HOSPITAL_SUCCESS';
export const DELETE_HOSPITAL_FAILURE = 'DELETE_HOSPITAL_FAILURE';

export const FETCH_MEDICAL_SPECIALISTS_SUCCESS = 'FETCH_MEDICAL_SPECIALISTS_SUCCESS';
export const FETCH_MEDICAL_SPECIALISTS_FAILURE = 'FETCH_MEDICAL_SPECIALISTS_FAILURE';
export const ADD_MEDICAL_SPECIALIST_SUCCESS = 'ADD_MEDICAL_SPECIALIST_SUCCESS';
export const ADD_MEDICAL_SPECIALIST_FAILURE = 'ADD_MEDICAL_SPECIALIST_FAILURE';
export const EDIT_MEDICAL_SPECIALIST_SUCCESS = 'EDIT_MEDICAL_SPECIALIST_SUCCESS';
export const EDIT_MEDICAL_SPECIALIST_FAILURE = 'EDIT_MEDICAL_SPECIALIST_FAILURE';
export const DELETE_MEDICAL_SPECIALIST_SUCCESS = 'DELETE_MEDICAL_SPECIALIST_SUCCESS';
export const DELETE_MEDICAL_SPECIALIST_FAILURE = 'DELETE_MEDICAL_SPECIALIST_FAILURE';

export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAILURE = 'FETCH_PATIENTS_FAILURE';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAILURE = 'ADD_PATIENT_FAILURE';
export const EDIT_PATIENT_SUCCESS = 'EDIT_PATIENT_SUCCESS';
export const EDIT_PATIENT_FAILURE = 'EDIT_PATIENT_FAILURE';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';

export const FETCH_REFERRALS_SUCCESS = 'FETCH_REFERRALS_SUCCESS';
export const FETCH_REFERRALS_FAILURE = 'FETCH_REFERRALS_FAILURE';
export const ADD_REFERRAL_SUCCESS = 'ADD_REFERRAL_SUCCESS';
export const ADD_REFERRAL_FAILURE = 'ADD_REFERRAL_FAILURE';
export const EDIT_REFERRAL_SUCCESS = 'EDIT_REFERRAL_SUCCESS';
export const EDIT_REFERRAL_FAILURE = 'EDIT_REFERRAL_FAILURE';
export const DELETE_REFERRAL_SUCCESS = 'DELETE_REFERRAL_SUCCESS';
export const DELETE_REFERRAL_FAILURE = 'DELETE_REFERRAL_FAILURE';
export const FETCH_REFERRAL_TYPES_SUCCESS = 'FETCH_REFERRAL_TYPES_SUCCESS';
export const FETCH_REFERRAL_TYPES_FAILURE = 'FETCH_REFERRAL_TYPES_FAILURE';

export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS';
export const VALIDATE_USER_FAILURE = 'VALIDATE_USER_FAILURE';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const EDIT_USER_INFO_FAILURE = 'EDIT_USER_INFO_FAILURE';
export const SET_INVALID_USER_NAME_AND_PASSWORD_VALUE = 'SET_INVALID_USER_NAME_AND_PASSWORD_VALUE';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
